### ISSUE TITLE
Checklist - Maltego Configuration File

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#19]
Select "_Custom Selection_"
- [x] Add "_Transform Hub Items_" -> "_Have I Been Pwned?_"

Select "_Entities_"
- [x] Add "_Penetration Testing_" -> "_Breach_"
- [ ] ~Add "_Penetration Testing_" -> "_Have I Been Pwned? Password_"~
- [x] Add "_cmlh_" -> "_Node_"
- [x] Add "_cmlh_" -> "_Error_"

Select "_Transform Sets_"
- [ ] ~Add "_Breached_"~
- [x] Add "_v2 Have I Been Pwned?_"
- [x] Add "_v3 Pwned Password_"

Select "_Machines_"
- [x] Add "_@haveibeenpwned E-mail_"
- [x] Add "_@haveibeenpwned Alias_"
- [x] Add "_@haveibeenpwned Pwned Password_"

Select "_Icons_"
- [x] Add "_@cmlh_" -> "_@haveibeenpwned_"
- [x] Add "_@cmlh_" -> "_Error_"

**Comment by cmlh** [comment]
Fix https://github.com/cmlh/Maltego-haveibeenpwned/commit/54951e5fa655e484b7673c5bead997f0bff95cdb

**Comment by cmlh** [comment]
Insert "_Pwned Password_" Machine

**Comment by cmlh** [comment]
Fix 05bb4a55025f87144ed2e9f89c854e3c1bb73c36
