### ISSUE TITLE
Checklist - Transform Configuration

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#20]
- [x] Transform Set

[iTDS Transforms Screen](https://cetas.paterva.com/TDS/transforms)

- [x] [Transform] Name
- [x] [Transform] UI Display
- [x] [Transform Metadata] Disclaimer
- [x] [Transform Metadata] Description

[Transform Hub XML Document](https://github.com/cmlh/Maltego-haveibeenpwned/blob/master/Transform_Hub/Transform_Hub.xml)

- [x] Description
- [ ] Details

**Comment by cmlh** [comment]
Fix https://github.com/cmlh/Maltego-haveibeenpwned/commit/54951e5fa655e484b7673c5bead997f0bff95cdb
