### ISSUE TITLE
Checklist - "Have I Been Pwned?" Acceptable Use Policy

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#21]
Insert link to "Have I Been Pwned?" [Acceptable Use](https://haveibeenpwned.com/api/v2/#AcceptableUse) policy in the `Disclaimer` field of each Maltego Transform's Metadata that uses API v2.

**API v2**
- [x] From "_Alias_" `maltego.Alias` To [`Breaches for Account v2`](https://haveibeenpwned.com/API/v2#BreachesForAccount)
- [x] From "_E-mail Address_" `maltego.EmailAddress` To [`Breaches for Account v2`](https://haveibeenpwned.com/API/v2#BreachesForAccount)
- [x] From "_E-mail Address_" `maltego.EmailAddress` To [`Pastes v2`](https://haveibeenpwned.com/API/v2#PastesForAccount)
- [x] From "_Breach_" `breach.Name` [`Getting a single breached site v2`](https://haveibeenpwned.com/API/v2#SingleBreach)
- [x] From "_Breach_" `breach.Name` To [`Getting all breached sites in the system v2`](https://haveibeenpwned.com/API/v2#AllBreaches)
- [x] From "_Domain_" `maltego.Domain` To [`Getting all breached sites in the system v2`](https://haveibeenpwned.com/API/v2#AllBreaches)
- [x] From "_Password_" `haveibeenpwned.Password` To [`Pwned Passwords`](https://haveibeenpwned.com/API/v2#PwnedPasswords)
- [x] From "_SHA-1 Hash_" `maltego.Hash` To [`Pwned Passwords`](https://haveibeenpwned.com/API/v2#PwnedPasswords)

1. From "_Breach_" `haveibeenpwned.breach` To "_Domain_" `maltego.Domain`

The **API v1** endpoints **are not** subject to the "Have I Been Pwned?" [Acceptable User](https://haveibeenpwned.com/api/v2/#AcceptableUse) policy [as it is applicable to the API v2 only].
1. From "_E-mail Address_" `maltego.EmailAddress` To [`Breaches for Account v1`](https://haveibeenpwned.com/API/v1)
2. From "_Alias_" `maltego.Alias` To [`Breaches for Account v1`](https://haveibeenpwned.com/API/v1)

**Comment by cmlh** [comment]
Fix #21
