### ISSUE TITLE
Checklist - Transform Metadata

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#22]
- [ ] From "_Breach_" `haveibeenpwned.breach` To "_Domain_" `maltego.Domain`

**API v2**
- [ ] From "_Alias_" `maltego.Alias` To [`Breaches for Account v2`](https://haveibeenpwned.com/API/v2#BreachesForAccount)
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`Breaches for Account v2`](https://haveibeenpwned.com/API/v2#BreachesForAccount)
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`Pastes v2`](https://haveibeenpwned.com/API/v2#PastesForAccount)
- [ ] From "_Breach_" `breach.Name` [`Getting a single breached site v2`](https://haveibeenpwned.com/API/v2#SingleBreach)
- [ ] From "_Breach_" `breach.Name` To [`Getting all breached sites in the system v2`](https://haveibeenpwned.com/API/v2#AllBreaches)
- [ ] From "_Domain_" `maltego.Domain` To [`Getting all breached sites in the system v2`](https://haveibeenpwned.com/API/v2#AllBreaches)
- [ ] From "_Password_" `haveibeenpwned.Password` To [`Pwned Passwords`](https://haveibeenpwned.com/API/v2#PwnedPasswords)
- [ ] From "_SHA-1 Hash_" `maltego.Hash` To [`Pwned Passwords`](https://haveibeenpwned.com/API/v2#PwnedPasswords)

**API v1**
- [ ] From "_E-mail Address_" `maltego.EmailAddress` To [`Breaches for Account v1`](https://haveibeenpwned.com/API/v1)
- [ ] From "_Alias_" `maltego.Alias` To [`Breaches for Account v1`](https://haveibeenpwned.com/API/v1)
