### ISSUE TITLE
Checklist - Maltego Configuration File - HIBP

### ISSUE THREAD

**Issue by cmlh** [cmlh/Maltego-haveibeenpwned#24]
Select "_Custom Selection_"
- [x] Add "_Transform Hub Items_" -> "_HIBP?_"

Select "_Entities_"
- [x] Add "_Penetration Testing_" -> "_Breach_"
- [x] Add "_cmlh_" -> "_Error_"

Select "_Transform Sets_"
- [ ] ~Add "_Breached_"~
- [x] Add "_v2 Have I Been Pwned?_"
- [x] Add "_v1 Have I Been Pwned?_"

Select "_Machines_"
- [x] Add "_@haveibeenpwned v1 E-mail_"
- [x] Add "_@haveibeenpwned v1 Alias_"

Select "_Icons_"
- [x] Add "_@cmlh_" -> "_@haveibeenpwned_"
- [x] Add "_@cmlh_" -> "_Error_"

**Comment by cmlh** [comment]
Fix https://github.com/cmlh/Maltego-haveibeenpwned/commit/07d643fd69fb58a1e7cd654003686bf674191322
